server {
    listen 443 ssl;
    server_name {{SERVER_NAMES}};

    ssl_certificate {{SSL_CERT_FILE}};
    ssl_certificate_key {{SSL_KEY_FILE}};

    access_log {{NGINX_LOG_DIR}}/{{HOST}}.access.log;
    error_log {{NGINX_LOG_DIR}}/{{HOST}}.error.log;

    error_page 421 = @wor_default;
    {{NGINX_HOST_CHECK}}

    {{NGINX_REDIRECT}}

    {{NGINX_SERVICE_CONFIG}}

    {{NGINX_CUSTOM_INCLUDE}}

    location @wor_default {
        internal;
        root {{DEFAULT_PUBLIC_PATH}};
        try_files /index.html =404;
    }
}
