package cliapp

import (
	"path/filepath"
	"strings"

	"wor/internal/hostprovider"
	"wor/internal/osutil"
)

// customConfigExampleName is the reference file wor writes into every
// service's custom-config directory. It deliberately does NOT end in
// ".conf" so the vhost's `*.conf` include never loads it: it is
// documentation, regenerated by wor on each host write, not live config.
const customConfigExampleName = "default.conf.example"

// writeCustomConfigScaffold creates the per-service custom web-server
// config directory that the generated vhost includes
// (<serviceDir>/.wor/<provider>) and refreshes the non-loaded reference
// file inside it. The reference shows wor's current default for this
// exact service plus the rules for adding snippets.
//
// It is best-effort: the include in the vhost tolerates an empty or
// missing directory, so a failure here is reported as a warning and never
// blocks writing the vhost itself.
func (a *App) writeCustomConfigScaffold(provider *hostprovider.Provider, params hostprovider.WriteParams) {
	if params.CustomConfigBaseDir == "" {
		return
	}
	dir := filepath.Join(params.CustomConfigBaseDir, provider.Name)
	if err := osutil.EnsureDir(dir); err != nil {
		a.warn("could not create custom-config dir %s: %s", dir, err)
		return
	}
	serviceConfig, err := provider.RenderServiceConfig(params)
	if err != nil {
		a.warn("could not render reference custom-config: %s", err)
		return
	}
	content := renderCustomConfigExample(provider.Name, dir, serviceConfig)
	examplePath := filepath.Join(dir, customConfigExampleName)
	if err := osutil.WriteFileAtomic(examplePath, []byte(content), 0o644); err != nil {
		a.warn("could not write reference custom-config %s: %s", examplePath, err)
	}
}

// renderCustomConfigExample builds the contents of the non-loaded
// reference file. providerName is "nginx" or "apache"; dir is the
// absolute custom-config directory; serviceConfig is wor's freshly
// rendered default service block for this host.
func renderCustomConfigExample(providerName, dir, serviceConfig string) string {
	var b strings.Builder
	line := func(s string) { b.WriteString(s + "\n") }

	line("# ============================================================")
	line("# wor custom web-server config -- REFERENCE ONLY (not loaded)")
	line("# ============================================================")
	line("#")
	line("# This file is NOT active. It does not match the include glob")
	line("# (*.conf) and wor regenerates it on every host write, so any")
	line("# edits here are lost -- do not edit it in place.")
	line("#")
	line("# To add your own config, create a NEW file in this folder:")
	line("#")
	line("#     " + filepath.Join(dir, "myrules.conf"))
	line("#")
	if providerName == "nginx" {
		line("# Every *.conf here is included INSIDE this service's")
		line("# `server { }` block, right after wor's own directives.")
		line("#")
		line("# Rules:")
		line("#   - You may ADD new `location` blocks / directives.")
		line("#   - You may NOT redefine a `location` wor already emits")
		line("#     (e.g. `location /`, `location ~ \\.php`): nginx rejects")
		line("#     duplicate locations with \"duplicate location\" on reload.")
	} else {
		line("# Every *.conf here is included INSIDE this service's")
		line("# <VirtualHost> (both :80 and :443), right after wor's own")
		line("# directives.")
		line("#")
		line("# Rules:")
		line("#   - You may ADD new directives / <Location> blocks.")
		line("#   - Avoid redeclaring directives that conflict with wor's")
		line("#     (e.g. a second DirectoryIndex or SetHandler for .php).")
	}
	line("#   - Reload after changes:  wor host reload")
	line("#")
	line("# ------------------------------------------------------------")
	line("# wor's current default for this service (for reference only):")
	line("# ------------------------------------------------------------")
	line("#")
	for _, l := range strings.Split(strings.TrimRight(serviceConfig, "\n"), "\n") {
		if l == "" {
			line("#")
			continue
		}
		line("# " + l)
	}
	line("#")
	line("# ------------------------------------------------------------")
	line("# Example addition -- copy into a real *.conf file to use:")
	line("# ------------------------------------------------------------")
	line("#")
	if providerName == "nginx" {
		line("# location = /healthz {")
		line("#     default_type text/plain;")
		line("#     return 200 \"ok\";")
		line("# }")
	} else {
		line("# <Location \"/healthz\">")
		line("#     Require all granted")
		line("# </Location>")
	}
	return b.String()
}
