// Package version is the single source of truth for wor's product name
// and release version number.
//
// It exists as its own leaf package (no imports of any other wor
// package) because both internal/cliapp (which prints these values in
// `wor version`/`--version`, the usage banner, and `wor doctor`) and
// internal/hostprovider (which stamps ProductName into the
// "Generated by ..." banner of every nginx/apache vhost config it
// writes) need it, and cliapp already imports hostprovider -- so
// hostprovider importing cliapp back would be a cycle. Putting these
// two constants here instead means renaming the product or cutting a
// new version is a one-file edit.
package version

import "strconv"

// ProductName is wor's display name: shown in `wor version`, the
// usage banner, `wor doctor`, and the "Generated by ..." comment at
// the top of every vhost config wor writes.
const ProductName = "WOR Host"

// Number is wor's release version string.
const Number = "1.0.1"

// Build is the release build number -- the running commit count that
// scripts/release.sh puts in a tag's "-b<n>" suffix (v1.0.1-b58 is
// build 58). Stamped at compile time by scripts/build.sh via
// -ldflags "-X wor/internal/version.Build=<n>", and empty in a binary
// built any other way (a plain `go build`, or a build outside a git
// work tree).
//
// A var rather than a const because -ldflags -X can only write to a
// var. Number stays a const: it is the value scripts/build.sh and
// scripts/release.sh read out of this file with sed, and the thing a
// human edits to cut a new version.
//
// This exists because Number alone cannot tell two releases apart.
// Version 1.0.1 covered builds 51 through 58, so `wor upgrade`
// comparing versions would have reported every one of them as current.
// Go embeds the commit SHA automatically (see cliapp.buildRevision) but
// not the commit *count*, and the count is what the published tag is
// named after.
var Build string

// BuildNumber returns Build as an integer, and whether it was stamped
// at all. Callers get (0, false) for an unstamped binary and must say
// so rather than treating it as build 0, which would compare as older
// than every real release.
func BuildNumber() (int, bool) {
	if Build == "" {
		return 0, false
	}
	n, err := strconv.Atoi(Build)
	if err != nil {
		return 0, false
	}
	return n, true
}
