// Package version is the single source of truth for wor's product name
// and release version number.
//
// It exists as its own leaf package (no imports of any other wor
// package) because both internal/cliapp (which prints these values in
// `wor version`/`--version`, the usage banner, and `wor doctor`) and
// internal/hostprovider (which stamps ProductName into the
// "Generated by ..." banner of every nginx/apache vhost config it
// writes) need it, and cliapp already imports hostprovider -- so
// hostprovider importing cliapp back would be a cycle. Putting these
// two constants here instead means renaming the product or cutting a
// new version is a one-file edit.
package version

// ProductName is wor's display name: shown in `wor version`, the
// usage banner, `wor doctor`, and the "Generated by ..." comment at
// the top of every vhost config wor writes.
const ProductName = "WOR Runtime Manager"

// Number is wor's release version string.
const Number = "1.0.0"
